### ISSUE TITLE
Modal Overlay Missing

### ISSUE THREAD

**Issue by KreepN** [m-e-conroy/angular-dialog-service#101]
Copied the example you provided [here](http://codepen.io/m-e-conroy/pen/DAxzs/) on your codepen and [updated most of the references to the most recent versions](http://codepen.io/KreepN/pen/JopYev).

You'll notice that when you open the modal, the overlay is no longer present. Any idea on what may have changed to cause this?

It looks as though the overlay no longer has a height, but I'm not of why that would have changed.

**Comment by KreepN** [comment]
Seems the styles in the bootstrap.css file have changed:

.modal-backdrop is now 'position: absolute' and the 'bottom: 0' has been removed. If you manually add them back onto your page the overlay works again.

**Comment by m-e-conroy** [comment]
@KreepN I keep having to fix either the backdrop or the modal itself with showing up, its usually something to do with the Bootstrap CSS changing.  I have CSS that accompanies the service but it may need updating to fix the specific Bootstrap change.  Also you can add your own classes to the "window" or backdrop by using the options object and `windowClass: 'my-class'` or `backdropClass: 'my-class'` this may help fix or thwart future CSS changes.
