### ISSUE TITLE
Integration with ui.router

### ISSUE THREAD

**Issue by Andradez** [m-e-conroy/angular-dialog-service#102]
Hello, Thank you for the excellent module.

I would like to integrate the dialog functionality with ui.router .

For example: If someone tries to access a  page that requires Login, a Login dialog
should show up.
I have the ui.router for this functionality already in place, i just do not know how to launch
the dialog when such condition occurs.

Example:  I tried to inject dialogsProvider in the angular.config(function(dialogsProvider) {
...
}

But  i get: Error: [$injector:unpr] Unknown provider: ,dialogsProvider <- ,dialogs

Please, Can you point me in the right direction?

Thanks

**Comment by m-e-conroy** [comment]
Apologies for getting back to you so late, but my real job keeps my extremely busy.

You should be injecting `$dialogsProvider` into the config function, you're missing the dollar sign.  You can create your own dialog interface by using the `dialogs.create` service and passing it the template, controller and any data you want.  [Check out this example](http://codepen.io/m-e-conroy/pen/DAxzs) which uses the `create` service of `dialogs` to create a custom dialog.
