### ISSUE TITLE
how to set it up in an existing project ?

### ISSUE THREAD

**Issue by jpca999** [m-e-conroy/angular-dialog-service#109]

**Comment by leal0t** [comment]
I would also like to know how to set this up in an existing project.

**Comment by m-e-conroy** [comment]
I will be adding setup & usage explanations when I get some time.

Right now you can bower install the service then include the `dialogs.min.js` file in your application.  Depending on your usage of Angular-Translate you may or may not want to also include `dialogs-default-translations.min.js`

Add `dialogs.main` to your module then inject the service `dialogs` into your controller, service, etc.

To call one of the services for example: `dialogs.notify('My Modal Header','My Modal Content');`
