### ISSUE TITLE
Page with overflow:scroll slides up when modal opens

### ISSUE THREAD

**Issue by aaronjessen** [m-e-conroy/angular-dialog-service#110]
Hello,

On a page where the body overflow is set to scroll, if the page is scrolled to anywhere but the top, the page scrolls to the top when opening the modal. Have you or anyone else noticed this behavior? If so, how can I stop it from happening?

**Comment by m-e-conroy** [comment]
This is beyond the scope of this project.

I would suggest asking the folks at [Angular-Bootstrap](http://angular-ui.github.io/), this also could be an issue with just the Bootstrap CSS itself.
