### ISSUE TITLE
Breaks angular-growl messages

### ISSUE THREAD

**Issue by cmbirk** [m-e-conroy/angular-dialog-service#112]
I'm using https://github.com/JanStevens/angular-growl-2 for quick messages, and when I import angular-dialog-service, the text of the growl messages no longer appear.  The boxes still appear, but have no text in them.

**Comment by m-e-conroy** [comment]
I'm going to take a quick guess at this and say that there is some conflict in the with Angular-Translate list of translations if you're using that.

**Comment by m-e-conroy** [comment]
I don't use angular-growl but I have used ngToast with this service and it works fine with no interference.

I'm sorry I really don't have the time to test this service with other angular modules.
