### ISSUE TITLE
List versions in README from highest to lowest

### ISSUE THREAD

**Issue by drasive** [m-e-conroy/angular-dialog-service#115]
I find it really hard to read the README because the version numbers are ordered from lowest to highest in some places, e.g. [Demos](../blob/8ef525e9cc74b473d0035efbc830caf0b24872d5/README.md#demos) (but not everywhere, e.g. the headers in [Releases](../blob/8ef525e9cc74b473d0035efbc830caf0b24872d5/README.md#release-versions)).  

I would be glad to reorder them myself, if this gets accepted.

**Comment by niemyjski** [comment]
Can you do a pull request for this. I'm trying to see if @m-e-conroy  will add me and @dougmoscrop to the repo to help out.
