### ISSUE TITLE
Dialogs don't dismiss with angular-bootstrap 0.13

### ISSUE THREAD

**Issue by djehring** [m-e-conroy/angular-dialog-service#117]
I recently updated angular-bootstrap to version 0.13, but found that the dialogs no longer dismiss by any button. I am using version 5.2.6 of the dialogs. Downgrading to 0.11 fixes the issue.

**Comment by faisalferoz** [comment]
In my case they do dismiss but the grey overlay stays there.

**Comment by leobudima** [comment]
Same problem...

**Comment by dlwhiteman** [comment]
Mine do not dismiss either.  Please fix this ASAP because angular-bootstrap 0.13 provides important functionality to my application.

**Comment by NeevShah** [comment]
I'm facing same problem.. please fix this ASAP...

**Comment by leobudima** [comment]
Problem is most likely with ngAnimate. 

https://github.com/angular-ui/bootstrap/issues/3694

It works if animation is disabled, but since it is not possible to send "animate: false" as an option through angular-dialog-service call, you need to edit the source and force it in each dialog method (error, wait, confirm...).

**Comment by niemyjski** [comment]
@m-e-conroy @leobudima  I also think it has to do with animation.. I'm seeing the same behavior... I had to add a resolution to ensure that "angular-animate": "~1.3.15" was used.. This is preventing me from upgrading to angular 1.4.

Also can we update the other dependencies like angular-translate and angular-bootstrap

 angular-dialog-service#5.2.6
│ ├── angular#1.3.15 (1.4.1-build.4029+sha.d7dc14d available)
│ ├── angular-bootstrap#0.13.0 incompatible with ~0.11 (0.11.2 available, latest is 0.13.0)
│ ├─┬ angular-sanitize#1.4.0 (1.4.1-build.4029+sha.d7dc14d available)
│ │ └── angular#1.3.15 incompatible with 1.4.0 (1.4.0 available, latest is 1.4.1-build.4029+sha.d7dc14d)
│ ├── angular-translate#2.1.0 (latest is 2.7.2)

**Comment by deeg** [comment]
Was anyone able to create a plunker showing the issue? When I tried the issue wasn't happening, which means there might be something else in my code which causes the issue.

**Comment by nmarshall23** [comment]
This happens to me too, when I add [Angular Toastr](https://github.com/Foxandxss/angular-toastr) directive to a controller that also has ui.bootstrap.modal. 

My page doesn't return from the faded out state. 

It has something to do with the version of ngAnimate used. Soon as the module depends on ngAnimate 1.4.0, the bug shows up, when a modal is closed.

**Comment by niemyjski** [comment]
hmm. I also have toastr installed.

On 6/3/15, Nicholas Marshall <notifications@github.com> wrote:
> This happens to me too, when I add [Angular
> Toastr](https://github.com/Foxandxss/angular-toastr) directive to a
> controller that also has ui.bootstrap.modal.
>
> My page doesn't return from the faded out state.
>
> It has something to do with the version of ngAnimate used. Soon as the
> module depends on ngAnimate 1.4.0, the bug shows up, when a modal is
> closed.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/m-e-conroy/angular-dialog-service/issues/117#issuecomment-108607003


-- 
Thanks
-Blake Niemyjski

**Comment by jberzins** [comment]
Issue with 1.4 animate and bootstrap https://github.com/angular-ui/bootstrap/issues/3633

Workaround by John:
angular.module('MY_MODULE_NAME').config(function($modalProvider) {
  $modalProvider.options.animation = false;
});

**Comment by m-e-conroy** [comment]
@jberzins Thank you for taking the time to figure this one out, and anyone else that suspected it was the ngAnimate issue with Angular 1.4

I apologize to everyone else, I've been super busy lately with my real job to actually work on this.  I will look into adding the above workaround directly into the dialogs service.

**Comment by m-e-conroy** [comment]
Added the ability to toggle animations on and off via modal options or turn on using `$dialogsProvider.useAnimation()` with an a config block as animations will be off by default seeing as its causing a problem.

**Comment by leobudima** [comment]
Thanks a lot, @m-e-conroy, really appreciate your effort and finding the time!

**Comment by trickpattyFH20** [comment]
is there any documentation or an example page on how to implement $dialogsProvider.useAnimation()?

**Comment by trickpattyFH20** [comment]
my problem is using animations on an ng-repeat within the modal, not on the transition to the modal itself. 

I know the animation is fine, it works in the parent view. the ng-enter and ng-leave classes are not added to an ng-repeat in a partial used with the angular-dialog-service

has anyone else run into this problem?
@m-e-conroy @leobudima
