### ISSUE TITLE
check if dialog is open using isOpen 

### ISSUE THREAD

**Issue by programming-kid** [m-e-conroy/angular-dialog-service#124]
there should be a function to check if particular dialog is open like ```isOpen``` using a dialog name or id specified while creating dialog

**Comment by niemyjski** [comment]
I've been using this code base since it's creation and haven't had a use case for this. Not saying this isn't a valid request but what behavior are you running into that you need this?

**Comment by programming-kid** [comment]
i have a login modal which is fired on 401 response so every time user enters wrong credentials another modal is opened so i need ```isOpen``` to check if login modal is already open

**Comment by dougmoscrop** [comment]
So, that's something you can track on your own though - the library provides a promise when it is opened. It can be as simple as having a service, or even just a simple `run` that keeps a local variable (isDialogOpened) and then only opens it if it is not already opened, etc.

**Comment by programming-kid** [comment]
yea i know it can be done but its not an elegant solution , i just wanted a clean solution

**Comment by dlwhiteman** [comment]
I was looking for the same thing, a way to find open dialogs so we don't need to open another instance if one is already open.

**Comment by dougmoscrop** [comment]
You can still track all this in your own service; have your 'offline' or 'connection problem' code/error handler emit an event, and have another piece that listens to those events and raises the dialog. In that place it's as simple as if () ... with a local var.
