### ISSUE TITLE
close all dialogs at once

### ISSUE THREAD

**Issue by programming-kid** [m-e-conroy/angular-dialog-service#125]
there has to be a global function ``closeAll()`` to close all open dialogs at once

thanks

**Comment by niemyjski** [comment]
When would you ever have more than one modal dialog open at a time?

**Comment by niemyjski** [comment]
You could also wire/fire an event to close the dialogs.

**Comment by dougmoscrop** [comment]
I'd also argue that stuff like this can easy be considered an additional library/module - you're getting in to "window manager" territory here, and that's baggage that people should opt in to and not have to pull in every time they want to present a dialog.

**Comment by niemyjski** [comment]
I agree

**Comment by dlwhiteman** [comment]
How would one create an event to close the dialogs?  Where do I find a handle for open dialogs?  I think I have a similar situation as the original poster, where when connectivity is restored, I want to close the dialogs that have been opened indicating the connection is down.

**Comment by dougmoscrop** [comment]
Why can't you keep that handle yourself in whatever spot is responsible for detecting a connectivity problem and raising the dialog?
