### ISSUE TITLE
Add support for ui-bootstrap 0.14+

### ISSUE THREAD

**Issue by NealHaggard** [m-e-conroy/angular-dialog-service#145]
They've renamed things including $modal to $uibModal (with 0.14.3 they will also rename $uibModalInstance).  Currently it still works using angular-dialog-service 5.2.8, however a warning is given about $modal being deprecated when dialogs is initialized.

**Comment by niemyjski** [comment]
Can you please include a pull request for this. I can confirm this behavior.

**Comment by NealHaggard** [comment]
Added a pull request. https://github.com/m-e-conroy/angular-dialog-service/pull/146/files

**Comment by niemyjski** [comment]
@NealHaggard Thanks for your contribution!

**Comment by niemyjski** [comment]
Is anyone getting this error?

`$modalInstance is now deprecated. Use $uibModalInstance instead.`

**Comment by NealHaggard** [comment]
Have you upgraded your code after using this?  dialog-service is now using ui-bootstrap 0.14.3 which will give those messages until you go change $modalInstance to $uibModalInstance (similarly $modal changed to $uibModal).  I don't get this in my local usage of angular-dialog-service 5.2.9 with ui-bootstrap 0.14.3.

**Comment by niemyjski** [comment]
Yeah, I'm running latest of everything!

https://github.com/exceptionless/Exceptionless.ui

I need to check for usages but I'm about 95% sure I'm not injecting $modalInstance

**Comment by NealHaggard** [comment]
Just a quick look through your code found this:

https://github.com/exceptionless/Exceptionless.UI/blob/master/src/components/dialog/confirm-dialog-controller.js

**Comment by niemyjski** [comment]
Ah thanks :)
