### ISSUE TITLE
dialogs.min.css isn't being updated

### ISSUE THREAD

**Issue by niemyjski** [m-e-conroy/angular-dialog-service#149]
@m-e-conroy Did you used to have a build step that updated this? I think for now we should remove this as end users should have minifiers.

**Comment by niemyjski** [comment]
@m-e-conroy Can we push a new update? There are a lot of good changes in 5.2.9

**Comment by niemyjski** [comment]
@m-e-conroy I can push a new release but I can't publish it on npm. Are you fine with me creating a 5.2.9 release?

**Comment by m-e-conroy** [comment]
Sure, go for it.

**Comment by niemyjski** [comment]
@m-e-conroy pushed https://github.com/m-e-conroy/angular-dialog-service/releases/tag/v5.2.9 You will want to publish with npm :) or feel free to add me to the npmjs account.

**Comment by m-e-conroy** [comment]
Great thanks. The bower site usually picks up the changes but I'll force it
if necessary.
