### ISSUE TITLE
How can I use it?example script has erroneous code 

### ISSUE THREAD

**Issue by 3223554** [m-e-conroy/angular-dialog-service#155]
console wirte
"Error: [$injector:unpr] http://errors.angularjs.org/1.2.25/$injector/unpr?p0=%24uibModalProvider%20%3C-%20%24uibModal%20%3C-%20dialogs
D/<@https://code.angularjs.org/1.2.25/angular.min.js:6:450
gc/l.$injector<@https://code.angularjs.org/1.2.25/angular.min.js:36:202
c@https://code.angularjs.org/1.2.25/angular.min.js:34:305
gc/p.$injector<@https://code.angularjs.org/1.2.25/angular.min.js:36:268
c@https://code.angularjs.org/1.2.25/angular.min.js:34:305
d@https://code.angularjs.org/1.2.25/angular.min.js:35:1
gc/p.$injector<@https://code.angularjs.org/1.2.25/angular.min.js:36:286
c@https://code.angularjs.org/1.2.25/angular.min.js:34:305

**Comment by 3223554** [comment]
run  example/index.html page error

**Comment by niemyjski** [comment]
I think all the examples need to be updated, they are probably running angular 1.2 and the library requires 1.4+

**Comment by niemyjski** [comment]
Would you mind submitting a pull request with the updated dependencies for the samples?

**Comment by 3223554** [comment]
Can you send an example of a running version to my email？
I downloaded the latest version of the sample but can't running

my e-mail:329247072@qq.com

**Comment by niemyjski** [comment]
@m-e-conroy  I've bumped the version for updated samples

@3223554 please see the updated samples
