### ISSUE TITLE
Upgrade to angular-bootstrap ~1.0?

### ISSUE THREAD

**Issue by jwohlfert23** [m-e-conroy/angular-dialog-service#164]

**Comment by niemyjski** [comment]
Would you submit a pull request for this.

**Comment by sargin48** [comment]
Heyyyyy conroy please upgrade,
or submit a pull request for this solutions
pufffff.

**Comment by niemyjski** [comment]
You guys are developers and can help out too.. Submit a pull request and bumb the version and I'll accept it and deploy

**Comment by sargin48** [comment]
Okey man  :+1: 

Those two plug-in versions(Bower &MPM) are different than each other, Bower is old. Could you update Bower version, or what should I do for updating Bower.  To which address should I send pull request in order to update Bower versiyon ?

**Comment by niemyjski** [comment]
you can update both files with the same exact version and dependencies and then just create a pull request that contains both the npm and bower files. You'd create the pr through github

**Comment by niemyjski** [comment]
Fixed in latest version
