### ISSUE TITLE
Call dialog from a bootstrap modal dialog - Position

### ISSUE THREAD

**Issue by felipeaffonso** [m-e-conroy/angular-dialog-service#165]
Hi,

I'm trying to use your service with angular-bootstrap-ui modal (I really use it), but the position on the screen is wrong.

I suppose that a dialog with a validation error should appear on TOP of the screen, maybe something is wrong with the Z-Index, OR (more probably) I'm doing something wrong.

Thanks!

**Comment by m-e-conroy** [comment]
Do you have an example we could see?  

There really is no CSS involved with this library (although there is a small CSS file that attempts to correct an old flaw in previous versions of Angular-Bootstrap-UI), if CSS is at fault its either with Bootstrap, Angular-Bootstrap-UI or a custom CSS class within your application.  All I can do is speculate without seeing something.

**Comment by alex3stones** [comment]
means, the dialog is on the back of modal window,instead of the top, tested this bug under angularjs 1.4.8 and angularjs-bootstrop-ui 1.3.2

**Comment by alex3stones** [comment]
![image](https://cloud.githubusercontent.com/assets/15151490/15701109/d57c7d2a-280a-11e6-898d-2a816308344e.png)

**Comment by m-e-conroy** [comment]
Not sure I understand.

The image shows that two dialogs have been opened.  If you don't want that, you need to close the other before opening a new one.  If you want the error dialog to show up over the dialog with the form I'm not sure we can help with that if the form dialog generated the error.  This library doesn't fiddle with the z-indexing of Bootstrap, it only calls predefined layouts using the Angular-UI Modal service.

**Comment by dougmoscrop** [comment]
It's totally up to the consumer of this library to do 'window management' which includes trying to overlay a dialog with a modal. The CSS is in your control, set your layers/z-indices appropriately.

**Comment by alex3stones** [comment]
@dougmoscrop: you are right. @m-e-conroy: any idea for this request? Thanks

**Comment by m-e-conroy** [comment]
I've had some minor CSS issues in the past with Bootstrap and Angular-UI and just used a small CSS file to fix.  If your intention is to have the error dialog pop-up over the form dialog then I would suggest adding a css class to it upon opening - to insure its above the other.  When passing in options to one of the dialog services you can set the "windowClass" property.  This will add a css class to the dialog's main element.  View the "IDialogOptions" of the readme for this library.
