### ISSUE TITLE
the translation for chinese does not work.

### ISSUE THREAD

**Issue by Agileaq** [m-e-conroy/angular-dialog-service#167]
I added one line
`<div class="col-md-12">
	<button class="btn btn-default" ng-click="setLanguage('en-US')">English</button>
	<button class="btn btn-default" ng-click="setLanguage('es')">Spanish</button>
	**<button class="btn btn-default" ng-click="setLanguage('zh-CN')">Chinese</button>**
</div>`
and changed the dialogTest.js file : 
`		$scope.$watch('lang',function(val,old){
			switch(val){
				case 'en-US':
					$scope.language = 'English';
					break;
				case 'es':
					$scope.language = 'Spanish';
					break;
**				case 'zh-CN':
					$scope.language = 'Chinese';
					break;**
			}
		});`
then I run index.html and click on the btn, I get gibberish...

![giblish](https://cloud.githubusercontent.com/assets/7555950/13105551/b4846cfe-d59e-11e5-8d24-6383a5e2b778.png)

**Comment by m-e-conroy** [comment]
Did you add the translations for Chinese?

This doesn't automatically translate text for you like Google Translate.  You need to supply the translations, all that happens is a substitution by Angular-Translate when the language setting is changed.
