### ISSUE TITLE
Support component param from angular bootstrap dialog

### ISSUE THREAD

**Issue by roychoo** [m-e-conroy/angular-dialog-service#190]
Hi,

I realised that `dialog.create` didn't support `component` param.

thus created PR #189 .

**Comment by niemyjski** [comment]
Thanks for the pr

**Comment by roychoo** [comment]
np @niemyjski may i know when would you do a release so that it contains this feature?

**Comment by niemyjski** [comment]
It would be nice if some of these other pr's went out with a release, would
you mind helping review them.

Thanks
-Blake Niemyjski

**Comment by roychoo** [comment]
Sure thanks for the reply. I will take a look later.
