### ISSUE TITLE
Option to provide custom confirm button text

### ISSUE THREAD

**Issue by niemyjski** [m-e-conroy/angular-dialog-service#66]
I looked through the code and only see the that the confirm text comes from the translator result. Is there a good way to set the confirm button (OK) button text. 

Examples of my confirm button text is 'Go to this action..',... 'Upgrade'

**Comment by obsidianart** [comment]
+1 It would be great to specify the labels as an option. Yes and No don't give any feedforward to the user and are usually considered bad UX, I prefer to inform the user to the exact meaning of pressing the buttons (like the button down here say "comment" instead of "send")

**Comment by dlwhiteman** [comment]
A big +1 to obsidianart's comment

**Comment by kanodoe** [comment]
+1 too

**Comment by bensan** [comment]
If anyone has an example of how to use decorators to change the labels on a per modal basis, I would appreciate if you would share it.

**Comment by guikubivan** [comment]
Any idea if this coming within the next month or so?

**Comment by niemyjski** [comment]
@guikubivan if you want to submit a pull request for this that would be a huge help.

**Comment by woodgoblin** [comment]
Are there any options to do it without overwriting template as for now?

**Comment by petran** [comment]
@niemyjski @m-e-conroy Does the custom text button works ?
I can see that the latest release is 5.3.0, How can I use version 5.3.1 ?

**Comment by niemyjski** [comment]
I have yet to push out a release, I was wanting to merge in some of the other pr's first. Would you mind reviewing them and leave any comments on them so we can have a bigger release
