### ISSUE TITLE
Allow the ControllerAs syntax

### ISSUE THREAD

**Issue by samudurand** [m-e-conroy/angular-dialog-service#85]
It would be really nice if it was possible to add a parameter allowing to set the 'ControllerAs' attribute of the modal. For a classic modal I would do something like : 

    function openListCreationForm() {
       var modalInstance = $modal.open({
       templateUrl: 'app/home/listCreationForm.tpl.html',
       controller: 'ListCreationModalController',
       controllerAs: 'lcf'
     });

     modalInstance.result.then(function () {
     }, function () {});
     }

for this project you could modify slightly your syntax with a parameter 'lcf' like this : 

  var dlgs = dialogs.create('app/home/listCreationForm.tpl.html', 'ListCreationModalController','lcf', {}, 'lg');

**Comment by samudurand** [comment]
:+1:

**Comment by venil7** [comment]
desperately need this functionality

**Comment by niemyjski** [comment]
Can you submit a pull request for this.

**Comment by venil7** [comment]
https://github.com/m-e-conroy/angular-dialog-service/pull/158

**Comment by niemyjski** [comment]
Change looks good to me. @samudurand can you test and verify it's good. Once I hear back I'll merge it.

**Comment by niemyjski** [comment]
Merged

**Comment by niemyjski** [comment]
@m-e-conroy 5.2.11 has been pushed

**Comment by m-e-conroy** [comment]
Sweet, thanks. Sorry haven't been able to participate much lately.
