### ISSUE TITLE
Angular 1.3?

### ISSUE THREAD

**Issue by LiamK** [m-e-conroy/angular-dialog-service#98]
Anyone tested this on Angular 1.3?

**Comment by wedneyyuri** [comment]
I am using it. I have not tested all the features yet.

**Comment by wedneyyuri** [comment]
#### Release Versions
**v5.2.5** : Better detection of Font-Awesome if style sheet has been concatentated. Tested against Angular 1.3.0 & Angular-Bootstrap 0.11.2

**Comment by KapuzenSohn** [comment]
Works for me.
Also used on the new AngularJs 1.4 Beta

**Comment by niemyjski** [comment]
Works for me

**Comment by ronnieoverby** [comment]
No problems for me.

**Comment by m-e-conroy** [comment]
I've used it with 1.3 and 1.4.

The combo of 1.4 with Angular-Bootstrap 0.13.0 and ngAnimate 1.4 causes a problem with modals not closing properly - I attempted to fix this v5.2.8 by defaulting animations to false.
